// Later tasks add their test imports here, e.g.:
//   import './world.test.ts';
//   import './entity.test.ts';
//   import './snapshot.test.ts';
import './transform.test.ts';
import './world.test.ts';
import './entity.test.ts';
import './entities.test.ts';
import './input.test.ts';
import './messages.test.ts';
import './time-sync.test.ts';
import './extrapolate.test.ts';
import './visual-smoothing.test.ts';
import './ping-server.test.ts';
import './network-client-sync.test.ts';
import './snapshot.test.ts';
import './physics-contract.test.ts';
import './rapier-body-sync.test.ts';
import './rapier-thrust-gating.test.ts';
import './fixed-timestep.test.ts';
import './projectile.test.ts';
import './weapon.test.ts';
import './combat.test.ts';
import './respawn.test.ts';
import './spawn.test.ts';
import './aim-math.test.ts';
import './steering.test.ts';
import './bot.test.ts';
import './vendor.test.ts';
import './names.test.ts';
import './mining.test.ts';
import './asteroid.test.ts';
import './mining-subsystem.test.ts';
import './respawn-asteroid.test.ts';
import './trade.test.ts';
import './progression.test.ts';
import './apply-extrapolation.test.ts';
import './rebind.test.ts';
import './quantize.test.ts';
import './bitpack.test.ts';
import { run } from './harness.ts';
run();
